source 'https://rubygems.org'

gem 'activesupport', '~> 7.0'
gem 'confidante', '0.28.0.pre.21'
gem 'docker-api', '~> 2.2'
gem 'dotenv', '~> 2.8'
gem 'nokogiri', '~> 1.13'
gem 'rake', '~> 13.0'
gem 'rake_docker', '~> 2.17'
gem 'rake_fly', '~> 2.11'
gem 'rake_leiningen', '~> 0.34'
gem 'rake_dependencies', '~> 3.1'
gem 'rake_terraform', '~> 1.23'
gem 'rake_vault', '0.1.0.pre.13'
gem 'semantic', '~> 1.6'
gem 'vault', '~> 0.17'